@echo off
call render_o 100 b1
call render_o 101 b1
call render_o 102 b1
call render_o 103 b1
call render_o 104 r
call render_o 105 b1
call render_o 106 b1
call render_o 107 b1
call render_o 108 b1
call render_o 111 b1
call render_o 112 b1
call render_o 113 b1
call render_o 114 b1
call render_o 115 b1
call render_o 116 b1
call render_o 117 b1
call render_o 118 b1
call render_o 119 b1
call render_o 151 b1
call render_o 152 b1
call render_o 153 b1
call render_o 154 b1
call render_o 155 b1
call render_o 156 b1
call render_o 158 b1
cls
echo Termin‚
